# This is a config for E2B sandbox template.
# You can use template ID (sbduww0t7ctcfhpmvmoj) or template name (lovable-clone) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("lovable-clone") # Sync sandbox
# sandbox = await AsyncSandbox.create("lovable-clone") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lovable-clone')

team_id = "03c9623c-7dd5-4406-81fa-0af85d67d0b9"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "lovable-clone"
template_id = "sbduww0t7ctcfhpmvmoj"
